import { HistorySnapshot, RgbaColor } from '../types';
export declare const DEFAULT_SWATCHES: string[];
export declare const createSnapshot: (ctx: CanvasRenderingContext2D, width: number, height: number, backgroundColor: string) => HistorySnapshot;
export declare const applySnapshot: (ctx: CanvasRenderingContext2D, snapshot: HistorySnapshot, backgroundCanvas: HTMLCanvasElement) => void;
export declare const drawLine: (ctx: CanvasRenderingContext2D, startX: number, startY: number, endX: number, endY: number, color: string, width: number, erase?: boolean) => void;
export declare const drawRectangle: (ctx: CanvasRenderingContext2D, startX: number, startY: number, width: number, height: number, strokeColor: string, strokeWidth: number, fillColor: string) => void;
export declare const drawCircle: (ctx: CanvasRenderingContext2D, startX: number, startY: number, width: number, height: number, strokeColor: string, strokeWidth: number, fillColor: string) => void;
export declare const drawSpray: (ctx: CanvasRenderingContext2D, x: number, y: number, radius: number, color: string) => void;
export declare const floodFill: (imageData: ImageData, x: number, y: number, fillColor: string) => boolean;
export declare const rgbaFromCanvas: (ctx: CanvasRenderingContext2D, x: number, y: number) => RgbaColor;
export declare const renderCompositeDataUrl: (drawingCanvas: HTMLCanvasElement, backgroundColor: string) => string;
